# Generated by Django 4.1.4 on 2022-12-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('fabricante', models.CharField(max_length=40)),
                ('cantidaddemotores', models.IntegerField(default=1)),
            ],
        ),
    ]
